In [1]:
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)




Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [2]:
# Check if the matrix is symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric? ", is_symmetric)


Is Matrix A symmetric?  False


In [3]:
# Your solution here
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

# Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)


Random Matrix:
 [[5 5 7 9]
 [5 1 9 1]
 [8 2 7 7]
 [1 6 6 5]]

Is the random matrix symmetric?  False


In [4]:
# Calculate the trace of matrix_A
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)



Trace of Matrix A: 15


# What is the trace of the following matrix?

In [7]:
matrix_B = np.array([
    [10, 20, 30],
    [5, 15, 25],
    [2, 4, 6]
])


trace_B = np.trace(matrix_B)


print("Trace of Matrix B:", trace_B)

Trace of Matrix B: 31


# Find the trace of a 5×5 identity matrix.

In [25]:

Matrix_A = np.array([
    [10, 20, 30, 40, 50],
    [5, 15, 25, 30, 35],
    [2, 4, 6, 8, 10],
    [3,6,9,12,15],
    [4,8,12,16,20]
    
])

trace_matrix = np.trace(Matrix_A)

print("5x5 Matrix:\n", Matrix_A)

print("Trace of the 5x5 identity matrix:", trace_matrix)



5x5 Matrix:
 [[10 20 30 40 50]
 [ 5 15 25 30 35]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]]
Trace of the 5x5 identity matrix: 63


# Compute the determinant of the following 3×3 matrix using NumPy:


In [27]:

matrix_D = np.array([
    [1, 2, 3],
    [0, 4, 5],
    [1, 0, 6]
])


M_11 = np.array([[4, 5], [0, 6]])  
M_12 = np.array([[0, 5], [1, 6]])  
M_13 = np.array([[0, 4], [1, 0]]) 

det_M11 = (M_11[0, 0] * M_11[1, 1]) - (M_11[0, 1] * M_11[1, 0])
det_M12 = (M_12[0, 0] * M_12[1, 1]) - (M_12[0, 1] * M_12[1, 0])
det_M13 = (M_13[0, 0] * M_13[1, 1]) - (M_13[0, 1] * M_13[1, 0])


det_D = (matrix_D[0, 0] * det_M11) - (matrix_D[0, 1] * det_M12) + (matrix_D[0, 2] * det_M13)


print("Determinant of Matrix D:", det_D)


Determinant of Matrix D: 22


# Practice Problem 4: Application in Computer Science

In [34]:
matrix_3x33 = np.random.randint(0, 256, size=(3, 33))
matrix_33x3 = np.random.randint(0, 256, size=(33, 3))

# Perform matrix multiplication
resultant_matrix = np.dot(matrix_3x33, matrix_33x3)

# Transpose and determinant
transpose = np.transpose(resultant_matrix)
determinant = np.linalg.det(resultant_matrix)

print("Transpose of the Resultant Matrix:", transpose)


print("Determinant of the Resultant Matrix:",determinant)


Transpose of the Resultant Matrix: [[517149 568806 613535]
 [540342 623861 696904]
 [474896 373315 468859]]
Determinant of the Resultant Matrix: 2859662904765633.5


# Practice Problem 5: Symmetric Matrices in Machine Learning

In [36]:
matrix = np.random.randint(0, 100, size=(3, 3))
symmetric_matrix = (matrix + matrix.T) // 2

# Verify symmetric properties
is_symmetric = np.array_equal(symmetric_matrix, symmetric_matrix.T)

symmetric_matrix, is_symmetricprint
("\nPractice Problem 5: Symmetric Matrix:",symmetric_matrix)
print)

print("\nPractice Problem 5: Is the matrix symmetric?")
print(is_symmetric)

NameError: name 'is_symmetricprint' is not defined